# Generated by Django 3.0.5 on 2021-02-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('adminupload', models.FileField(upload_to='newspaper')),
                ('desc', models.TextField()),
            ],
        ),
    ]
