# Generated by Django 3.0.5 on 2021-02-20 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_newspaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='book'),
            preserve_default=False,
        ),
    ]
