# Generated by Django 3.0.6 on 2021-05-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_eml'),
    ]

    operations = [
        migrations.AddField(
            model_name='eml',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
