# Generated by Django 3.0.6 on 2021-05-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_currentaffairs_generalscience_geography_history_polity'),
    ]

    operations = [
        migrations.CreateModel(
            name='impupdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='currentaffairs',
            name='qst',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='generalscience',
            name='qst',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='geography',
            name='qst',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='history',
            name='qst',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='polity',
            name='qst',
            field=models.TextField(max_length=300),
        ),
    ]
