# Generated by Django 3.2.4 on 2021-07-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210702_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='gjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='pics')),
                ('desc', models.CharField(max_length=350)),
                ('description', models.TextField()),
                ('slug', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='pjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='pics')),
                ('desc', models.CharField(max_length=350)),
                ('description', models.TextField()),
                ('slug', models.CharField(max_length=150)),
            ],
        ),
    ]
